#!/bin/sh

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝

# 01001101 01101001 01101110 01101001 01000010 01100101 01100001 01110011 01110100

SCRIPTS=$HOME/.config/bspwm/scripts

#  __  __          _ _                  __  ___         _   _
# |  \/  |___ _ _ (_) |_ ___ _ _ ___   / / |   \ ___ __| |_| |_ ___ _ __ ___
# | |\/| / _ \ ' \| |  _/ _ \ '_(_-<  / /  | |) / -_|_-< / /  _/ _ \ '_ (_-<
# |_|  |_\___/_||_|_|\__\___/_| /__/ /_/   |___/\___/__/_\_\\__\___/ .__/__/
#                                                                  |_|

HDMI1="xrandr | awk '/HDMI-1/ {print $2}'"

bspc monitor eDP -d 1 2 3 4 5
[[ $HDMI1 =~ connected ]] && bspc monitor HDMI-1 -d 6 7 8

#   ___       _   _
#  / _ \ _ __| |_(_)___ _ _  ___
# | (_) | '_ \  _| / _ \ ' \(_-<
#  \___/| .__/\__|_\___/_||_/__/
#       |_|

bspc config pointer_follows_monitor     true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config automatic_scheme            alternate
bspc config pointer_modifier            mod4
bspc config border_width                0
bspc config window_gap                  12
bspc config top_padding                 22
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config single_monocle              true

#   ___     _
#  / __|___| |___ _ _ ___
# | (__/ _ \ / _ \ '_(_-<
#  \___\___/_\___/_| /__/

bspc config normal_border_color         "333333"
bspc config active_border_color         "333333"
bspc config focused_border_color        "333333"
bspc config presel_feedback_color       "2980b9"

#  ___      _
# | _ \_  _| |___ ___
# |   / || | / -_|_-<
# |_|_\\_,_|_\___/__/


bspc rule -a Gimp state=floating follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam state=floating border=off follow=on
bspc rule -a Lutris state=floating border=off follow=on
bspc rule -a Sxiv state=floating follow=on
bspc rule -a Kodi state=fullscreen

#  ___         _      _
# / __| __ _ _(_)_ __| |_ ___
# \__ \/ _| '_| | '_ \  _(_-<
# |___/\__|_| |_| .__/\__/__/
#               |_|

$SCRIPTS/bspwm_floating &
$SCRIPTS/bspswallow &

#    _       _          _            _
#   /_\ _  _| |_ ___ __| |_ __ _ _ _| |_
#  / _ \ || |  _/ _ (_-<  _/ _` | '_|  _|
# /_/ \_\_,_|\__\___/__/\__\__,_|_|  \__|

sxhkd &
picom -f &
polybar_launch &
pcmanfm --desktop &
deadd-notification-center &
polkit-bspwm &
udiskie --tray
